const API="/api";let tasks=[];let editId=null;
const $=id=>document.getElementById(id), token=()=>localStorage.getItem("token");
$("loginTab").onclick=()=>switchAuth(true);$("registerTab").onclick=()=>switchAuth(false);
function switchAuth(login){$("loginTab").classList.toggle("active",login);$("registerTab").classList.toggle("active",!login);$("loginForm").classList.toggle("hidden",!login);$("registerForm").classList.toggle("hidden",login);$("authMessage").textContent=""}
$("registerForm").onsubmit=async e=>{e.preventDefault();try{const r=await fetch(API+"/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("registerName").value,email:$("registerEmail").value,password:$("registerPassword").value})});const d=await r.json();if(!r.ok)throw Error(d.message);saveLogin(d)}catch(x){$("authMessage").textContent=x.message}};
$("loginForm").onsubmit=async e=>{e.preventDefault();try{const r=await fetch(API+"/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("loginEmail").value,password:$("loginPassword").value})});const d=await r.json();if(!r.ok)throw Error(d.message);saveLogin(d)}catch(x){$("authMessage").textContent=x.message}};
function saveLogin(d){localStorage.setItem("token",d.token);localStorage.setItem("user",JSON.stringify(d.user));showApp()}
$("logoutBtn").onclick=()=>{localStorage.clear();location.reload()};
$("taskForm").onsubmit=async e=>{e.preventDefault();let data={title:$("taskTitle").value,description:$("taskDescription").value,priority:$("taskPriority").value,dueDate:$("taskDueDate").value};try{let url=API+"/tasks",method="POST";if(editId){url+="/"+editId;method="PUT";data.status=tasks.find(t=>t._id===editId).status}const r=await fetch(url,{method,headers:{"Content-Type":"application/json",Authorization:"Bearer "+token()},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.message);resetForm();loadTasks()}catch(x){$("taskMessage").textContent=x.message}};
$("cancelEditBtn").onclick=resetForm;$("searchInput").oninput=render;$("statusFilter").onchange=render;
async function loadTasks(){const r=await fetch(API+"/tasks",{headers:{Authorization:"Bearer "+token()}});if(r.status===401){localStorage.clear();location.reload();return}tasks=await r.json();render();stats()}
function render(){let q=$("searchInput").value.toLowerCase(),s=$("statusFilter").value;let list=tasks.filter(t=>(t.title.toLowerCase().includes(q)||t.description.toLowerCase().includes(q))&&(s==="All"||t.status===s));$("taskList").innerHTML=list.length?list.map(t=>`<div class="task ${t.status==="Completed"?"done":""}"><h3>${esc(t.title)}</h3><p>${esc(t.description||"No description")}</p><span class="badge">Priority: ${t.priority}</span><span class="badge">Status: ${t.status}</span><span class="badge">Due: ${t.dueDate||"None"}</span><div class="actions"><button onclick="toggleTask('${t._id}')">${t.status==="Completed"?"Reopen":"Complete"}</button><button onclick="editTask('${t._id}')">Edit</button><button class="delete" onclick="deleteTask('${t._id}')">Delete</button></div></div>`).join(""):'<p class="empty">No tasks found.</p>'}
function stats(){let c=tasks.filter(t=>t.status==="Completed").length;$("totalCount").textContent=tasks.length;$("completedCount").textContent=c;$("pendingCount").textContent=tasks.length-c}
window.toggleTask=async id=>{let t=tasks.find(x=>x._id===id);await update(id,{...t,status:t.status==="Completed"?"Pending":"Completed"})};
window.editTask=id=>{let t=tasks.find(x=>x._id===id);editId=id;$("formTitle").textContent="Edit Task";$("taskTitle").value=t.title;$("taskDescription").value=t.description;$("taskPriority").value=t.priority;$("taskDueDate").value=t.dueDate;$("saveTaskBtn").textContent="Update Task";$("cancelEditBtn").classList.remove("hidden");scrollTo(0,0)};
window.deleteTask=async id=>{if(!confirm("Delete this task?"))return;await fetch(API+"/tasks/"+id,{method:"DELETE",headers:{Authorization:"Bearer "+token()}});loadTasks()};
async function update(id,data){await fetch(API+"/tasks/"+id,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token()},body:JSON.stringify(data)});loadTasks()}
function resetForm(){editId=null;$("taskForm").reset();$("taskPriority").value="Medium";$("formTitle").textContent="Add New Task";$("saveTaskBtn").textContent="Add Task";$("cancelEditBtn").classList.add("hidden")}
function showApp(){let u=JSON.parse(localStorage.getItem("user"));$("authPage").classList.add("hidden");$("appPage").classList.remove("hidden");$("welcomeText").textContent="Welcome, "+u.name;loadTasks()}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
if(token())showApp();